spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
  topics: ${KAFKA_SUBSCRIBED_TOPICS}
server:
  port: 8082

bot:
  token: ${BOT_TOKEN}
  name: ${BOT_NAME}


topics: ${KAFKA_SUBSCRIBED_TOPICS}

logging:
  level:
    org.hibernate.SQL: DEBUG
